POST http://localhost:8000/api/v1/texts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDc5ODE4My1iOTMwLTRiMzctYTE1Ni1kMDNlM2FlMDY1ZTAiLCJpYXQiOjE1MzU3NjcxMTAsImV4cCI6MTU0MzU0MzExMH0.uvRxcbB-wCKspZe3FV-FQkl-uWswSBsV08OKUl1PvipBEkDU3f4zDfPVTTjAugSIAJ_WanU0gfGLTyRG92QA4p8hiReqh3LdTP5gNct1ETLUM4zpSOgFn-z7slSHAC1yf6XubL-X2Yba7UTnWWcx5h4r7Xb8sI32vGQ6NChTjdmqqbnRgzqmTrYQGuY-asF0e0auIw_rqnoTHnFujmYndfmQydHiguk_i7jiBEeEp4n1iIAGHdMpfQtqgqUdeEgO-aiOAUZkCSnGYe64iVjzbf9vxORFmEJv7abYc0o2vlDZT3wa8YdehKzTtKZRPGjlLCvUVpKQm65U9RqUvdexDB0D1rZXTaehk27OnO1J7MdAQ9UkCxZCONtQv6pmZHrCQdV7TA3HES9-hlzCxavzXaq-Mof32_UazcakII0pQIDP1NTxuJfqSvaHTr-ai67ryKMaMzJegLCMGySVJu_mzm-TvTM4U1e0LLvuGaj71rhi8GKVZ8g5O5b8O396f24RbiulkwJL_PR1dBcaqF5zDc3O90kiHDxDdgJTdeSLF7rQGXRNhz46u23UKeCKeQ2XeINs5cklQMWQrkYJznJ8gETrMzy4amzF0qr2lHKx90_fUs_NpxXwfsC8xcEHbnUOT7UEtZ9C9Djdgyw3v3KDJXh1OTQDGw4lNbJkOzRCdEg

{
    "language": "pt-BR",
    "input": "Preciso que me informe o érrigêì de sua conta para continuarmos o atendimento.",
    "type": "LINEAR16"
}

####

POST http://localhost:8000/api/v1/speechs
Content-Type: application/octet-stream
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDc5ODE4My1iOTMwLTRiMzctYTE1Ni1kMDNlM2FlMDY1ZTAiLCJpYXQiOjE1MzU3NjcxMTAsImV4cCI6MTU0MzU0MzExMH0.uvRxcbB-wCKspZe3FV-FQkl-uWswSBsV08OKUl1PvipBEkDU3f4zDfPVTTjAugSIAJ_WanU0gfGLTyRG92QA4p8hiReqh3LdTP5gNct1ETLUM4zpSOgFn-z7slSHAC1yf6XubL-X2Yba7UTnWWcx5h4r7Xb8sI32vGQ6NChTjdmqqbnRgzqmTrYQGuY-asF0e0auIw_rqnoTHnFujmYndfmQydHiguk_i7jiBEeEp4n1iIAGHdMpfQtqgqUdeEgO-aiOAUZkCSnGYe64iVjzbf9vxORFmEJv7abYc0o2vlDZT3wa8YdehKzTtKZRPGjlLCvUVpKQm65U9RqUvdexDB0D1rZXTaehk27OnO1J7MdAQ9UkCxZCONtQv6pmZHrCQdV7TA3HES9-hlzCxavzXaq-Mof32_UazcakII0pQIDP1NTxuJfqSvaHTr-ai67ryKMaMzJegLCMGySVJu_mzm-TvTM4U1e0LLvuGaj71rhi8GKVZ8g5O5b8O396f24RbiulkwJL_PR1dBcaqF5zDc3O90kiHDxDdgJTdeSLF7rQGXRNhz46u23UKeCKeQ2XeINs5cklQMWQrkYJznJ8gETrMzy4amzF0qr2lHKx90_fUs_NpxXwfsC8xcEHbnUOT7UEtZ9C9Djdgyw3v3KDJXh1OTQDGw4lNbJkOzRCdEg

"/home/iqueiroz/Downloads/transcript-google.wav"

###
